controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    camera_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster


camera_velocity_controller:
  ros__parameters:
    joints:
      - camera_joint
